//========================================================
//==================={  Global Fetch  }===================
//========================================================
const fetchConfig = {
  method: 'GET',
  mode: 'cors' as RequestMode,
  cache: 'default' as RequestCache, // Cacheing is *surely* our friend here... yes?
  headers: {
    'Content-Type': 'application/json',
    'Access-Control-Allow-Origin': '*',
  },
};
export const fetchData = async (url: string) => await fetch(url, fetchConfig).then((response) => response.json());
//========================================================
//========================================================

// Convert a response from the onthesnow api to a usable geo object
export const configurePointForMap = (resorts: any) => {
  // Use this to check other possible fields.
  return Promise.resolve({
    type: 'FeatureCollection',
    features: resorts.map((r: any, index: any) => {
      return {
        type: 'Feature',
        geometry: {
          type: 'Point',
          coordinates: [r.lng, r.lat],
        },

        // FORMATTED STRINGS for component.
        properties: {
          id: index,
          name: r.title,
          snowNew: r.snow.last24,
          snowBase: r.snow.base,
          snowSummit: r.snow.summit,
          liftsOpen: `${r.lifts.open} / ${r.lifts.total}`,
          runsOpen: `${r.runs.open} / ${r.runs.total} (${r.runs.open}%)`,
          image: r.snowReport?.smallImage,
          trailMap: r.snowReport?.trailMap.image,
          acresOpen: r.snowReport.acres?.open,
          acresTotal: r.snowReport.acres?.total,
          summit: r.elevation?.summit,
          vertical: r.elevation?.verticalDrop,
          base: r.elevation?.base,
        },
      };
    }),
  });
};

//=========================
// FRONTEND STUFF
//=========================

export const cmToIn = (cm: number) => Math.round(cm * 0.393701);
export const mToFt = (m: number) => Math.round(m * 3.28084);

// const exampleResort = {
//   uuid: '1',
//   title: '49 Degrees North',
//   title_short: '49° North',
//   title_original: '49 Degrees North',
//   slug: '49-degrees-north',
//   region: 'washington',
//   region_id: '206',
//   domain: null,
//   surfaceType: 1,
//   snow: {
//     last24: 20.32,
//     base: 96.52,
//     middle: null,
//     summit: 152.4,
//     last72: 30.48,
//   },
//   lifts: {
//     open: 7,
//     total: 7,
//   },
//   runs: {
//     open: 86,
//     openPercent: 97,
//     total: 89,
//   },
//   km: {
//     open: null,
//     total: 0,
//   },
//   status: {
//     openFlag: 1,
//     openingDate: '2022-12-03',
//     closingDate: '2023-04-09',
//   },
//   updatedAt: '2022-12-29T15:54:36+00:00',
//   currentWeather: {
//     date: '2022-12-28',
//     wind: 1.1,
//     snow: 20.32,
//     base: {
//       min: -7.4,
//       max: -1.4,
//     },
//     summit: {
//       min: -10,
//       max: -4,
//     },
//     type: 'CLOUDY',
//   },
//   lat: 48.28866943,
//   lng: -117.5561507,
//   snowReport: {
//     uuid: '1',
//     title: '49 Degrees North',
//     slug: '49-degrees-north',
//     corporateName: '49 DEGREES NORTH MTN. RESORT',
//     latitude: 48.28866943,
//     longitude: -117.5561507,
//     physicalAddress: '3311 Flowery Trail Rd.',
//     physicalCity: 'Chewelah',
//     zip: '99109',
//     timezone: -8,
//     region: {
//       uuid: '206',
//       slug: 'washington',
//       group: '429',
//       title: 'Washington',
//       country: 'United States',
//       country_code: 'USA',
//       adCode: 'snow/USA_PNW/WA',
//       state: 'WA',
//       domain: null,
//       countryUuid: '429',
//       continentUuid: '477',
//       stateUuid: '206',
//       isLogical: false,
//     },
//     image: 'https://img3.onthesnow.com/image/xl/54/49_degrees_north_3_544142.jpg',
//     imageTitle: '49 Degrees North 3',
//     imageCaption: 'Tommy Frey skis the powder at 49 Degrees North. Photo courtesy of 49 Degrees North.',
//     imageCreditLine: {
//       url: '',
//       title: '',
//     },
//     smallImage: 'https://img3.onthesnow.com/image/la/54/49_degrees_north_3_544142.jpg',
//     video: null,
//     website: null,
//     mobileWebsite: null,
//     phone: '(866) 376-4949',
//     isPartner: false,
//     twitter: null,
//     liftsUrl: null,
//     rentalUrl: null,
//     lessonsUrl: null,
//     surfaceType: 1,
//     surfaceTypeBottom: 4,
//     snow: {
//       last24: 20.32,
//       base: 96.52,
//       middle: null,
//       summit: 152.4,
//       last72: 30.48,
//     },
//     lifts: {
//       open: 7,
//       total: 7,
//     },
//     runs: {
//       open: 86,
//       openPercent: 97,
//       total: 89,
//     },
//     status: {
//       openFlag: 1,
//       openingDate: '2022-12-03',
//       closingDate: '2023-04-09',
//     },
//     updatedAt: '2022-12-29T15:54:36+00:00',
//     snowconeUuid: '7484769',
//     reportStatus: 2,
//     currentWeather: {
//       date: '2022-12-28',
//       wind: 1.1,
//       snow: 20.32,
//       base: {
//         min: -7.4,
//         max: -1.4,
//       },
//       summit: {
//         min: -10,
//         max: -4,
//       },
//       type: 'CLOUDY',
//     },
//     terrain: {
//       lifts: {
//         open: 7,
//         total: 7,
//       },
//       runs: {
//         open: 86,
//         openPercent: 97,
//         total: 89,
//       },
//       runsBeginner: {
//         openNum: null,
//         openLen: null,
//         openPercent: null,
//         totalLen: 0,
//         total: 0,
//         totalPercent: 30,
//       },
//       runsIntermediate: {
//         openNum: null,
//         openLen: null,
//         openPercent: null,
//         totalLen: 0,
//         total: 0,
//         totalPercent: 40,
//       },
//       runsAdvanced: {
//         openNum: null,
//         openLen: null,
//         openPercent: null,
//         totalLen: 0,
//         total: 0,
//         totalPercent: 25,
//       },
//       runsExpert: {
//         openNum: null,
//         openLen: null,
//         openPercent: null,
//         totalLen: 0,
//         total: 0,
//         totalPercent: 5,
//       },
//       acres: {
//         open: null,
//         total: 2325,
//       },
//       km: {
//         open: null,
//         total: 0,
//       },
//       parks: {
//         open: 1,
//         total: 2,
//       },
//       pipes: {
//         open: null,
//         total: 0,
//       },
//       tubes: {
//         open: null,
//         total: 0,
//       },
//       nordic: {
//         open: null,
//         trackset: null,
//         skategroomed: null,
//         total: 25,
//       },
//       canReturnBySki: null,
//     },
//     depthes: {
//       base: {
//         min: 96.52,
//         max: 96.52,
//       },
//       middle: {
//         min: null,
//         max: null,
//       },
//       summit: {
//         min: 152.4,
//         max: 152.4,
//       },
//     },
//     recent: [
//       {
//         date: '2022-12-22',
//         snow: 0,
//       },
//       {
//         date: '2022-12-23',
//         snow: 3,
//       },
//       {
//         date: '2022-12-24',
//         snow: 13,
//       },
//       {
//         date: '2022-12-25',
//         snow: 3,
//       },
//       {
//         date: '2022-12-26',
//         snow: 3,
//       },
//       {
//         date: '2022-12-27',
//         snow: 0,
//       },
//       {
//         date: '2022-12-28',
//         snow: 10,
//       },
//       {
//         date: '2022-12-29',
//         snow: 20,
//       },
//     ],
//     recentStartingReportedDate: '2022-12-29T00:00:00+00:00',
//     recentLastModified: '2022-12-29T15:54:36+00:00',
//     forecast: [
//       {
//         date: '2022-12-29',
//         snow: 20.32,
//       },
//       {
//         date: '2022-12-30',
//         snow: 7,
//       },
//       {
//         date: '2022-12-31',
//         snow: 0,
//       },
//       {
//         date: '2023-01-01',
//         snow: 0,
//       },
//       {
//         date: '2023-01-02',
//         snow: 0,
//       },
//       {
//         date: '2023-01-03',
//         snow: 0,
//       },
//       {
//         date: '2023-01-04',
//         snow: 8,
//       },
//       {
//         date: '2023-01-05',
//         snow: 0,
//       },
//     ],
//     history: null,
//     schedule: [
//       {
//         day: 0,
//         from: '09:00:00',
//         to: '16:00:00',
//         isNight: false,
//       },
//       {
//         day: 1,
//         from: '09:00:00',
//         to: '16:00:00',
//         isNight: false,
//       },
//       {
//         day: 2,
//         from: '09:00:00',
//         to: '16:00:00',
//         isNight: false,
//       },
//       {
//         day: 3,
//         from: '09:00:00',
//         to: '16:00:00',
//         isNight: false,
//       },
//       {
//         day: 4,
//         from: '09:00:00',
//         to: '16:00:00',
//         isNight: false,
//       },
//       {
//         day: 5,
//         from: '09:00:00',
//         to: '16:00:00',
//         isNight: false,
//       },
//       {
//         day: 6,
//         from: '09:00:00',
//         to: '16:00:00',
//         isNight: false,
//       },
//     ],
//     comment: null,
//     trailMap: {
//       uuid: '1',
//       source: null,
//       image: 'https://s3.onthesnow.com/images/trailmaps/washington/49-degrees-north/20190202175326/xlarge.jpg',
//       large: 'https://s3.onthesnow.com/images/trailmaps/washington/49-degrees-north/20190202175326/large.jpg',
//       medium: 'https://s3.onthesnow.com/images/trailmaps/washington/49-degrees-north/20190202175326/mid.jpg',
//       thumbnail: 'https://s3.onthesnow.com/images/trailmaps/washington/49-degrees-north/20190202175326/large.jpg',
//       iPhoneFull: 'https://s3.onthesnow.com/images/trailmaps/washington/49-degrees-north/20190202175326/iphonefull.jpg',
//       iPhoneThumb:
//         'https://s3.onthesnow.com/images/trailmaps/washington/49-degrees-north/20190202175326/iphonethumb.jpg',
//       size: 3338877,
//       dateModifiedEpoch: 1549130008,
//       shortInfo: null,
//       longInfo: null,
//     },
//     webcams: [
//       {
//         uuid: '4183',
//         title: '49 North Mountain Resort Lodge Cam ',
//         date: '2022-12-29T23:28:10+00:00',
//         image: 'https://www.onthesnow.com/webcams/1/4183/2022-12-29_2328/xl.jpg',
//         thumbnail: 'https://www.onthesnow.com/webcams/1/4183/2022-12-29_2328/la.jpg',
//         snow: {
//           date: '2022-12-29',
//           snow: 20.32,
//         },
//         summitSnowDepth: 152.4,
//         isFeatured: false,
//         videoStream: null,
//         webcamType: 0,
//         sort: 1,
//       },
//       {
//         uuid: '4184',
//         title: '49 Degrees North Summit Cam ',
//         date: '2022-12-29T23:28:11+00:00',
//         image: 'https://www.onthesnow.com/webcams/1/4184/2022-12-29_2328/xl.jpg',
//         thumbnail: 'https://www.onthesnow.com/webcams/1/4184/2022-12-29_2328/la.jpg',
//         snow: {
//           date: '2022-12-29',
//           snow: 20.32,
//         },
//         summitSnowDepth: 152.4,
//         isFeatured: false,
//         videoStream: null,
//         webcamType: 0,
//         sort: 2,
//       },
//       {
//         uuid: '22926',
//         title: '49 Degrees North - Sunrise Basin Cam',
//         date: '2022-12-29T23:29:29+00:00',
//         image: 'https://www.onthesnow.com/webcams/1/22926/2022-12-29_2329/xl.jpg',
//         thumbnail: 'https://www.onthesnow.com/webcams/1/22926/2022-12-29_2329/la.jpg',
//         snow: {
//           date: '2022-12-29',
//           snow: 20.32,
//         },
//         summitSnowDepth: 152.4,
//         isFeatured: false,
//         videoStream: null,
//         webcamType: 0,
//         sort: 3,
//       },
//     ],
//     weather: [
//       {
//         reportedDate: '2022-12-22',
//         modifiedDate: '2022-12-22',
//         windDirectionName: 'E',
//         windSpeedMps: 2.5,
//         weatherSymbol: 'CLOUDY',
//         iconId: 0,
//         tempHigh: -20.4,
//         tempLow: -27.5,
//         snowfall: 0,
//         conditionsIcon: null,
//         conditionId: null,
//         isForecast: false,
//         isReported: true,
//         bottomWindDirectionName: 'E',
//         bottomWindSpeedMps: 2.5,
//         bottomWeatherSymbol: 'CLOUDY',
//         bottomTempHigh: -17.8,
//         bottomTempLow: -24.9,
//         bottomTemp: -20.1,
//         topTemp: -22.7,
//         visibilityBottom: null,
//         visibilityTop: null,
//         surfaceTop: 1,
//         surfaceBottom: 4,
//         surfaceOffPisteTop: 0,
//         surfaceOffPisteBottom: 0,
//         altitude: 1619,
//         nday: 7,
//         windIconTop: '3_E',
//         windIconBottom: '3_E',
//       },
//       {
//         reportedDate: '2022-12-23',
//         modifiedDate: '2022-12-23',
//         windDirectionName: 'E',
//         windSpeedMps: 1.5,
//         weatherSymbol: 'SNOW_SHOWERS',
//         iconId: 0,
//         tempHigh: -13.3,
//         tempLow: -21,
//         snowfall: 2.54,
//         conditionsIcon: null,
//         conditionId: null,
//         isForecast: false,
//         isReported: true,
//         bottomWindDirectionName: 'E',
//         bottomWindSpeedMps: 1.5,
//         bottomWeatherSymbol: 'SNOW_SHOWERS',
//         bottomTempHigh: -10.7,
//         bottomTempLow: -18.4,
//         bottomTemp: -14,
//         topTemp: -16.6,
//         visibilityBottom: null,
//         visibilityTop: null,
//         surfaceTop: 1,
//         surfaceBottom: 4,
//         surfaceOffPisteTop: 0,
//         surfaceOffPisteBottom: 0,
//         altitude: 1619,
//         nday: 6,
//         windIconTop: '2_E',
//         windIconBottom: '2_E',
//       },
//       {
//         reportedDate: '2022-12-24',
//         modifiedDate: '2022-12-24',
//         windDirectionName: 'E',
//         windSpeedMps: 2.1,
//         weatherSymbol: 'SNOW',
//         iconId: 0,
//         tempHigh: -5.8,
//         tempLow: -15.7,
//         snowfall: 12.7,
//         conditionsIcon: null,
//         conditionId: null,
//         isForecast: false,
//         isReported: true,
//         bottomWindDirectionName: 'E',
//         bottomWindSpeedMps: 2.1,
//         bottomWeatherSymbol: 'SNOW',
//         bottomTempHigh: -3.2,
//         bottomTempLow: -13.1,
//         bottomTemp: -6.4,
//         topTemp: -9,
//         visibilityBottom: null,
//         visibilityTop: null,
//         surfaceTop: 2,
//         surfaceBottom: 0,
//         surfaceOffPisteTop: 0,
//         surfaceOffPisteBottom: 0,
//         altitude: 1619,
//         nday: 5,
//         windIconTop: '2_E',
//         windIconBottom: '2_E',
//       },
//       {
//         reportedDate: '2022-12-25',
//         modifiedDate: '2022-12-25',
//         windDirectionName: 'SE',
//         windSpeedMps: 0.8,
//         weatherSymbol: 'SNOW',
//         iconId: 0,
//         tempHigh: -2.6,
//         tempLow: -10.1,
//         snowfall: 2.54,
//         conditionsIcon: null,
//         conditionId: null,
//         isForecast: false,
//         isReported: true,
//         bottomWindDirectionName: 'SE',
//         bottomWindSpeedMps: 0.8,
//         bottomWeatherSymbol: 'SNOW',
//         bottomTempHigh: 0,
//         bottomTempLow: -7.5,
//         bottomTemp: -1.7,
//         topTemp: -4.3,
//         visibilityBottom: null,
//         visibilityTop: null,
//         surfaceTop: 1,
//         surfaceBottom: 0,
//         surfaceOffPisteTop: 0,
//         surfaceOffPisteBottom: 0,
//         altitude: 1619,
//         nday: 4,
//         windIconTop: '1_SE',
//         windIconBottom: '1_SE',
//       },
//       {
//         reportedDate: '2022-12-26',
//         modifiedDate: '2022-12-26',
//         windDirectionName: 'S',
//         windSpeedMps: 1.9,
//         weatherSymbol: 'SNOW',
//         iconId: 0,
//         tempHigh: -1.4,
//         tempLow: -3.3,
//         snowfall: 2.54,
//         conditionsIcon: null,
//         conditionId: null,
//         isForecast: false,
//         isReported: true,
//         bottomWindDirectionName: 'S',
//         bottomWindSpeedMps: 1.9,
//         bottomWeatherSymbol: 'SLEET',
//         bottomTempHigh: 1.2,
//         bottomTempLow: -0.7,
//         bottomTemp: 0.7,
//         topTemp: -1.9,
//         visibilityBottom: null,
//         visibilityTop: null,
//         surfaceTop: 4,
//         surfaceBottom: 2,
//         surfaceOffPisteTop: 0,
//         surfaceOffPisteBottom: 0,
//         altitude: 1619,
//         nday: 3,
//         windIconTop: '2_S',
//         windIconBottom: '2_S',
//       },
//       {
//         reportedDate: '2022-12-27',
//         modifiedDate: '2022-12-27',
//         windDirectionName: 'S',
//         windSpeedMps: 3.7,
//         weatherSymbol: 'SNOW_SHOWERS',
//         iconId: 0,
//         tempHigh: 0.2,
//         tempLow: -3.7,
//         snowfall: 0,
//         conditionsIcon: null,
//         conditionId: null,
//         isForecast: false,
//         isReported: true,
//         bottomWindDirectionName: 'S',
//         bottomWindSpeedMps: 3.7,
//         bottomWeatherSymbol: 'RAIN_SHOWERS',
//         bottomTempHigh: 2.8,
//         bottomTempLow: -1.1,
//         bottomTemp: 2.6,
//         topTemp: 0,
//         visibilityBottom: null,
//         visibilityTop: null,
//         surfaceTop: 4,
//         surfaceBottom: 2,
//         surfaceOffPisteTop: 0,
//         surfaceOffPisteBottom: 0,
//         altitude: 1619,
//         nday: 2,
//         windIconTop: '4_S',
//         windIconBottom: '4_S',
//       },
//       {
//         reportedDate: '2022-12-28',
//         modifiedDate: '2022-12-29',
//         windDirectionName: 'SW',
//         windSpeedMps: 2.1,
//         weatherSymbol: 'CLOUDY',
//         iconId: 0,
//         tempHigh: -3.7,
//         tempLow: -9.4,
//         snowfall: 10.16,
//         conditionsIcon: null,
//         conditionId: null,
//         isForecast: false,
//         isReported: true,
//         bottomWindDirectionName: 'SW',
//         bottomWindSpeedMps: 2.1,
//         bottomWeatherSymbol: 'CLOUDY',
//         bottomTempHigh: -1.1,
//         bottomTempLow: -6.8,
//         bottomTemp: -1.5,
//         topTemp: -4.1,
//         visibilityBottom: null,
//         visibilityTop: null,
//         surfaceTop: 1,
//         surfaceBottom: 4,
//         surfaceOffPisteTop: 0,
//         surfaceOffPisteBottom: 0,
//         altitude: 1619,
//         nday: 1,
//         windIconTop: '2_SW',
//         windIconBottom: '2_SW',
//       },
//       {
//         reportedDate: '2022-12-29',
//         modifiedDate: '2022-12-29',
//         windDirectionName: 'E',
//         windSpeedMps: 1.1,
//         weatherSymbol: 'CLOUDY',
//         iconId: 0,
//         tempHigh: -4,
//         tempLow: -10,
//         snowfall: 20.32,
//         conditionsIcon: null,
//         conditionId: null,
//         isForecast: false,
//         isReported: true,
//         bottomWindDirectionName: 'E',
//         bottomWindSpeedMps: 1.1,
//         bottomWeatherSymbol: 'CLOUDY',
//         bottomTempHigh: -1.4,
//         bottomTempLow: -7.4,
//         bottomTemp: -3,
//         topTemp: -5.6,
//         visibilityBottom: null,
//         visibilityTop: null,
//         surfaceTop: 1,
//         surfaceBottom: 4,
//         surfaceOffPisteTop: 0,
//         surfaceOffPisteBottom: 0,
//         altitude: 1619,
//         nday: 0,
//         windIconTop: '1_E',
//         windIconBottom: '1_E',
//       },
//       {
//         reportedDate: '2022-12-30',
//         modifiedDate: '2022-12-29',
//         windDirectionName: 'S',
//         windSpeedMps: 2.3,
//         weatherSymbol: 'FOG',
//         iconId: 0,
//         tempHigh: -3.5,
//         tempLow: -5.7,
//         snowfall: 7,
//         conditionsIcon: null,
//         conditionId: null,
//         isForecast: true,
//         isReported: false,
//         bottomWindDirectionName: 'S',
//         bottomWindSpeedMps: 2.3,
//         bottomWeatherSymbol: 'FOG',
//         bottomTempHigh: -0.9,
//         bottomTempLow: -3.1,
//         bottomTemp: -1.7,
//         topTemp: -4.3,
//         visibilityBottom: null,
//         visibilityTop: null,
//         surfaceTop: 0,
//         surfaceBottom: 0,
//         surfaceOffPisteTop: 0,
//         surfaceOffPisteBottom: 0,
//         altitude: 1619,
//         nday: -1,
//         windIconTop: '2_S',
//         windIconBottom: '2_S',
//       },
//       {
//         reportedDate: '2022-12-31',
//         modifiedDate: '2022-12-29',
//         windDirectionName: 'S',
//         windSpeedMps: 1.4,
//         weatherSymbol: 'FOG',
//         iconId: 0,
//         tempHigh: -4,
//         tempLow: -6.6,
//         snowfall: 0,
//         conditionsIcon: null,
//         conditionId: null,
//         isForecast: true,
//         isReported: false,
//         bottomWindDirectionName: 'S',
//         bottomWindSpeedMps: 1.4,
//         bottomWeatherSymbol: 'FOG',
//         bottomTempHigh: -1.4,
//         bottomTempLow: -4,
//         bottomTemp: -2.3,
//         topTemp: -4.9,
//         visibilityBottom: null,
//         visibilityTop: null,
//         surfaceTop: 0,
//         surfaceBottom: 0,
//         surfaceOffPisteTop: 0,
//         surfaceOffPisteBottom: 0,
//         altitude: 1619,
//         nday: -2,
//         windIconTop: '1_S',
//         windIconBottom: '1_S',
//       },
//       {
//         reportedDate: '2023-01-01',
//         modifiedDate: '2022-12-29',
//         windDirectionName: 'SE',
//         windSpeedMps: 0.4,
//         weatherSymbol: 'CLOUDY',
//         iconId: 0,
//         tempHigh: -6.6,
//         tempLow: -7.8,
//         snowfall: 0,
//         conditionsIcon: null,
//         conditionId: null,
//         isForecast: true,
//         isReported: false,
//         bottomWindDirectionName: 'SE',
//         bottomWindSpeedMps: 0.4,
//         bottomWeatherSymbol: 'CLOUDY',
//         bottomTempHigh: -4,
//         bottomTempLow: -5.2,
//         bottomTemp: -4.3,
//         topTemp: -6.9,
//         visibilityBottom: null,
//         visibilityTop: null,
//         surfaceTop: 0,
//         surfaceBottom: 0,
//         surfaceOffPisteTop: 0,
//         surfaceOffPisteBottom: 0,
//         altitude: 1619,
//         nday: 28,
//         windIconTop: '1_SE',
//         windIconBottom: '1_SE',
//       },
//       {
//         reportedDate: '2023-01-02',
//         modifiedDate: '2022-12-29',
//         windDirectionName: 'NE',
//         windSpeedMps: 1.4,
//         weatherSymbol: 'CLOUDY',
//         iconId: 0,
//         tempHigh: -7.7,
//         tempLow: -8.5,
//         snowfall: 0,
//         conditionsIcon: null,
//         conditionId: null,
//         isForecast: true,
//         isReported: false,
//         bottomWindDirectionName: 'NE',
//         bottomWindSpeedMps: 1.4,
//         bottomWeatherSymbol: 'CLOUDY',
//         bottomTempHigh: -5.1,
//         bottomTempLow: -5.9,
//         bottomTemp: -5.1,
//         topTemp: -7.7,
//         visibilityBottom: null,
//         visibilityTop: null,
//         surfaceTop: 0,
//         surfaceBottom: 0,
//         surfaceOffPisteTop: 0,
//         surfaceOffPisteBottom: 0,
//         altitude: 1619,
//         nday: 27,
//         windIconTop: '1_NE',
//         windIconBottom: '1_NE',
//       },
//       {
//         reportedDate: '2023-01-03',
//         modifiedDate: '2022-12-29',
//         windDirectionName: 'E',
//         windSpeedMps: 1.1,
//         weatherSymbol: 'CLOUDY',
//         iconId: 0,
//         tempHigh: -8.7,
//         tempLow: -12,
//         snowfall: 0,
//         conditionsIcon: null,
//         conditionId: null,
//         isForecast: true,
//         isReported: false,
//         bottomWindDirectionName: 'E',
//         bottomWindSpeedMps: 1.1,
//         bottomWeatherSymbol: 'CLOUDY',
//         bottomTempHigh: -6.1,
//         bottomTempLow: -9.4,
//         bottomTemp: -7,
//         topTemp: -9.6,
//         visibilityBottom: null,
//         visibilityTop: null,
//         surfaceTop: 0,
//         surfaceBottom: 0,
//         surfaceOffPisteTop: 0,
//         surfaceOffPisteBottom: 0,
//         altitude: 1619,
//         nday: 26,
//         windIconTop: '1_E',
//         windIconBottom: '1_E',
//       },
//       {
//         reportedDate: '2023-01-04',
//         modifiedDate: '2022-12-29',
//         windDirectionName: 'E',
//         windSpeedMps: 3.6,
//         weatherSymbol: 'SNOW',
//         iconId: 0,
//         tempHigh: -5.6,
//         tempLow: -8.7,
//         snowfall: 8,
//         conditionsIcon: null,
//         conditionId: null,
//         isForecast: true,
//         isReported: false,
//         bottomWindDirectionName: 'E',
//         bottomWindSpeedMps: 3.6,
//         bottomWeatherSymbol: 'SNOW',
//         bottomTempHigh: -3,
//         bottomTempLow: -6.1,
//         bottomTemp: -4.6,
//         topTemp: -7.2,
//         visibilityBottom: null,
//         visibilityTop: null,
//         surfaceTop: 0,
//         surfaceBottom: 0,
//         surfaceOffPisteTop: 0,
//         surfaceOffPisteBottom: 0,
//         altitude: 1619,
//         nday: 25,
//         windIconTop: '4_E',
//         windIconBottom: '4_E',
//       },
//       {
//         reportedDate: '2023-01-05',
//         modifiedDate: '2022-12-29',
//         windDirectionName: 'E',
//         windSpeedMps: 0.4,
//         weatherSymbol: 'CLOUDY',
//         iconId: 0,
//         tempHigh: -3.5,
//         tempLow: -5,
//         snowfall: 0,
//         conditionsIcon: null,
//         conditionId: null,
//         isForecast: true,
//         isReported: false,
//         bottomWindDirectionName: 'E',
//         bottomWindSpeedMps: 0.4,
//         bottomWeatherSymbol: 'CLOUDY',
//         bottomTempHigh: -0.9,
//         bottomTempLow: -2.4,
//         bottomTemp: -0.9,
//         topTemp: -3.5,
//         visibilityBottom: null,
//         visibilityTop: null,
//         surfaceTop: 0,
//         surfaceBottom: 0,
//         surfaceOffPisteTop: 0,
//         surfaceOffPisteBottom: 0,
//         altitude: 1619,
//         nday: 24,
//         windIconTop: '1_E',
//         windIconBottom: '1_E',
//       },
//     ],
//   },
// };
